--- 
title: "Minicurso de R Shiny"
author: "Frederico L Souza"
date: "`r Sys.Date()`"
output:
  # rmdformats::chaos:
  rmdformats::downcute:
    downcute_theme: "chaos"
    self_contained: true
    thumbnails: true
    #lightbox: true
    gallery: false
    highlight: tango    
    # toc: yes
    # toc_float: yes
  pdf_document:
    toc: yes
link-citations: yes
fontsize: 18pt
# description: Minicurso de SQL aplicado à Pesquisa Distrital por Amostra de Domicílios - PDAD, ano-base 2018
---

```{r, echo=F}
# library(knitr)
# library(stringr)
# library(forcats)

# Definir opções dos chunks
# knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE,
                       # results = "hide")

# Definir função para separador de milhar e decimal dos chunks
# knit_hooks$set(inline = function(x) {
#   prettyNum(x, big.mark=".",decimal.mark = ",")
# })

# Outras opções gerais e de pacotes específicos
# options(OutDec = ",")
# options(scipen=999)
# setwd("C:/Users/37010/Documents/GitHub/curso_r_shiny/")
```

# Agenda

Este minicurso de R Shiny terá enfoque na introdução na plataforma de painéis open-source para subsidiar os trabalhos desenvolvidos no ***Instituto de Pesquisa e Estatística do DF - IPEDF Codeplan***, com o intuito de mostrar outras maneiras de disponibilizar as informações produzidas pelas pessoas.

# 1	Introdução 

## 1.1	O que é R Shiny

É uma aplicação web em R que permite você transformar seus dados/relatórios em uma interface web.

## 1.2	Como que funciona?

Um Shiny app tem dois componentes

- Script de controle da interface (controles de layout e aparência que converte o código em R em comandos de HTML);

- Script servidor (código necessário para construção da aplicação).

## 1.3	É necessário saber HTML

Nenhum conhecimento em HTML, CSS ou JavaScript é necessário, mas é possível utilizar para fazer alterações/melhorias na interface.

# 2	Iniciando

## 2.1	 Estrutura mínima de arquivos



## 2.2	Funções de interface (ui.R)

### 2.2.1	Formatação de texto

### 2.2.2	Adicionar imagens

### 2.2.3	Adicionar Widgets

## 2.3	Parte servidor (sever.R)

# 3 Tipos de painéis

# 4	Como usar em aplicações externas

